{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bra-simple-java-maven-deploy.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "bra-simple-java-maven-deploy.name" . }}
    helm.sh/chart: {{ include "bra-simple-java-maven-deploy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: {{ $ingressPath }}
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: 5678
{{- end }}