pipeline {
    stages {
        stage('Build') {
            steps {
                sh 'echo "Build"'
            }
        }
        stage('Test') {
            steps {
                sh 'echo test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo Deliver'
            }
        }
    }
}
