name: Build and Publish DevOps Tools

on:
 push:
   branches: [ master ]

jobs:
  build-image:   
    runs-on: self‑hosted

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    name: build-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Deploy via ArgoCD utilizando username e password
        uses: diegograssato/argocd-gh-action@v1.0.0
        with:
          argocd_server: ${{ secrets.ARGOCD_SERVER }}
          argocd_username: ${{ secrets.ARGOCD_USERNAME }}
          argocd_password: ${{ secrets.ARGOCD_PASSWORD }}
          argocd_applications: "gha-runner-scale-set-sample"
          refresh: "true"
          sync: "true"
          insecure: "true"
          prune: "false"
 
       