name: Build and Publish DevOps Tools

on:
 push:
   branches: [ master ]

jobs:
  build-image:   
    runs-on: keda

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    name: build-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
   
      - name: Test docker
        run: |
         docker images
         docker ps


      - name: Deploy via ArgoCD utilizando token
        uses: diegograssato/argocd-gh-action@v1.0.0
        with:
          argocd_server: ${{ secrets.ARGOCD_SERVER }}
          argocd_token: ${{ secrets.ARGOCD_TOKEN }}
          argocd_applications: "sample-dev"
          refresh: "true"
          sync: "true"
          insecure: "false"
          prune: "true"
 
       