name: Build and Publish DevOps Tools

on:
 push:
   branches: [ master ]

jobs:
  build-image:   
    runs-on: gha-runner-scaleset-sample

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    name: build-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Deploy via ArgoCD utilizando token
        uses: diegograssato/argocd-gh-action@v1.0.0
        with:
          argocd_server: ${{ secrets.ARGOCD_SERVER }}
          argocd_token: ${{ secrets.ARGOCD_TOKEN }}
          argocd_applications: "gha-runner-scale-set-sample"
          refresh: "false"
          sync: "true"
          insecure: "false"
          prune: "false"
 
       